<?xml version="1.0" encoding="utf-8"?><Database Name="HubServiceEgisz" Class="HubServiceEgiszDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=HubServiceEgisz;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HubServiceEgiszConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.F001" Member="F001">
    <Type Name="F001">
      <Column Name="tf_code" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="tf_okato" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="tf_ogrn" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="name_tfp" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="name_tfk" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="post_index" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="fam_dir" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="im_dir" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ot_dir" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="fax" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="e_mail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="kf_tf" Type="System.Decimal" DbType="Decimal(4,0) NOT NULL" CanBeNull="false" />
      <Column Name="www" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="d_edit" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="d_end" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>