#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceNsi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HubServiceEgisz")]
	public partial class HubServiceEgiszDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    #endregion
		
		public HubServiceEgiszDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HubServiceEgiszConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HubServiceEgiszDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HubServiceEgiszDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HubServiceEgiszDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HubServiceEgiszDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<F001> F001
		{
			get
			{
				return this.GetTable<F001>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.F001")]
	public partial class F001
	{
		
		private string _tf_code;
		
		private string _tf_okato;
		
		private string _tf_ogrn;
		
		private string _name_tfp;
		
		private string _name_tfk;
		
		private string _post_index;
		
		private string _address;
		
		private string _fam_dir;
		
		private string _im_dir;
		
		private string _ot_dir;
		
		private string _phone;
		
		private string _fax;
		
		private string _e_mail;
		
		private decimal? _kf_tf;
		
		private string _www;
		
		private System.DateTime _d_edit;
		
		private System.Nullable<System.DateTime> _d_end;
		
		public F001()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tf_code", DbType="NVarChar(2)")]
		public string tf_code
		{
			get
			{
				return this._tf_code;
			}
			set
			{
				if ((this._tf_code != value))
				{
					this._tf_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tf_okato", DbType="NVarChar(5)")]
		public string tf_okato
		{
			get
			{
				return this._tf_okato;
			}
			set
			{
				if ((this._tf_okato != value))
				{
					this._tf_okato = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tf_ogrn", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string tf_ogrn
		{
			get
			{
				return this._tf_ogrn;
			}
			set
			{
				if ((this._tf_ogrn != value))
				{
					this._tf_ogrn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_tfp", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string name_tfp
		{
			get
			{
				return this._name_tfp;
			}
			set
			{
				if ((this._name_tfp != value))
				{
					this._name_tfp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_tfk", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string name_tfk
		{
			get
			{
				return this._name_tfk;
			}
			set
			{
				if ((this._name_tfk != value))
				{
					this._name_tfk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_index", DbType="NVarChar(6)")]
		public string post_index
		{
			get
			{
				return this._post_index;
			}
			set
			{
				if ((this._post_index != value))
				{
					this._post_index = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fam_dir", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string fam_dir
		{
			get
			{
				return this._fam_dir;
			}
			set
			{
				if ((this._fam_dir != value))
				{
					this._fam_dir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_im_dir", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string im_dir
		{
			get
			{
				return this._im_dir;
			}
			set
			{
				if ((this._im_dir != value))
				{
					this._im_dir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ot_dir", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string ot_dir
		{
			get
			{
				return this._ot_dir;
			}
			set
			{
				if ((this._ot_dir != value))
				{
					this._ot_dir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this._fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_mail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string e_mail
		{
			get
			{
				return this._e_mail;
			}
			set
			{
				if ((this._e_mail != value))
				{
					this._e_mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kf_tf", DbType="Decimal(4,0) NOT NULL")]
		public decimal? kf_tf
		{
			get
			{
				return this._kf_tf;
			}
			set
			{
				if ((this._kf_tf != value))
				{
					this._kf_tf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_www", DbType="NVarChar(100)")]
		public string www
		{
			get
			{
				return this._www;
			}
			set
			{
				if ((this._www != value))
				{
					this._www = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_edit", DbType="DateTime NOT NULL")]
		public System.DateTime d_edit
		{
			get
			{
				return this._d_edit;
			}
			set
			{
				if ((this._d_edit != value))
				{
					this._d_edit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_end", DbType="DateTime")]
		public System.Nullable<System.DateTime> d_end
		{
			get
			{
				return this._d_end;
			}
			set
			{
				if ((this._d_end != value))
				{
					this._d_end = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
